spring:
  application:

    name: heimaai
  ai:
     openai:
        api-key: your-api-key
        base-url: your-base-url
        chat:
          options:
            model: your-model
server:
  port: 8082
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.example.ai: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
